services:
  db:
    image: bitnami/postgresql:latest
    container_name: postgres_db36
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: harvel
    ports:
      - '5432:5432'
    volumes:
      - 'db_data:/bitnami/postgresql'
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: api-pgadmin-36
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: bieelerick9876@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234567
    ports:
      - '16543:80'
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
